// This file defines the countryScores object used by the AOI interactive map.
// It is generated from the Allied Opportunities Index methodology and includes
// allied and economic scores for every ISO‑2 country code. Each entry
// contains the human‑readable country name along with the allied and
// economic scores on a 0–10 scale. Territories inherit scores from their
// parent countries where appropriate.

const countryScores = {

  "AD": { name: "Andorra", allied: 8.01, economic: 9.27 },
  "AE": { name: "United Arab Emirates", allied: 1.72, economic: 8.91 },
  "AF": { name: "Afghanistan", allied: 1.22, economic: 3.63 },
  "AG": { name: "Antigua and Barbuda", allied: 7.59, economic: 7.25 },
  "AL": { name: "Albania", allied: 8.34, economic: 7.88 },
  "AM": { name: "Armenia", allied: 5.40, economic: 6.65 },
  "AO": { name: "Angola", allied: 2.15, economic: 3.18 },
  "AR": { name: "Argentina", allied: 8.67, economic: 7.19 },
  "AT": { name: "Austria", allied: 8.01, economic: 8.62 },
  "AU": { name: "Australia", allied: 9.40, economic: 9.23 },
  "AZ": { name: "Azerbaijan", allied: 1.26, economic: 6.26 },
  "BA": { name: "Bosnia and Herzegovina", allied: 5.32, economic: 7.33 },
  "BB": { name: "Barbados", allied: 8.05, economic: 6.81 },
  "BD": { name: "Bangladesh", allied: 4.02, economic: 6.33 },
  "BE": { name: "Belgium", allied: 9.52, economic: 8.67 },
  "BF": { name: "Burkina Faso", allied: 2.02, economic: 2.00 },
  "BG": { name: "Bulgaria", allied: 7.31, economic: 6.60 },
  "BH": { name: "Bahrain", allied: 1.08, economic: 7.84 },
  "BI": { name: "Burundi", allied: 1.52, economic: 3.37 },
  "BJ": { name: "Benin", allied: 5.25, economic: 2.31 },
  "BL": { name: "Saint Barthelemy", allied: 9.24, economic: 9.05 },
  "BM": { name: "Bermuda", allied: 9.40, economic: 8.77 },
  "BN": { name: "Brunei", allied: 2.10, economic: 6.54 },
  "BO": { name: "Bolivia", allied: 6.05, economic: 4.79 },
  "BQBO": { name: "Bonaire", allied: 9.40, economic: 8.77 },
  "BQSA": { name: "Sint Eustatius", allied: 9.40, economic: 8.77 },
  "BQSE": { name: "Saba", allied: 9.40, economic: 8.77 },
  "BR": { name: "Brazil", allied: 8.12, economic: 6.70 },
  "BS": { name: "Bahamas", allied: 8.90, economic: 6.60 },
  "BT": { name: "Bhutan", allied: 6.59, economic: 5.56 },
  "BW": { name: "Botswana", allied: 7.27, economic: 4.24 },
  "BY": { name: "Belarus", allied: 0.69, economic: 5.04 },
  "BZ": { name: "Belize", allied: 8.53, economic: 5.59 },
  "CA": { name: "Canada", allied: 9.23, economic: 8.53 },
  "CD": { name: "Democratic Republic of Congo", allied: 1.48, economic: 2.13 },
  "CF": { name: "Central African Republic", allied: 0.97, economic: 1.49 },
  "CG": { name: "Republic of the Congo", allied: 1.25, economic: 3.25 },
  "CH": { name: "Switzerland", allied: 9.48, economic: 8.82 },
  "CI": { name: "Cote d'Ivoire", allied: 4.61, economic: 2.28 },
  "CL": { name: "Chile", allied: 8.93, economic: 7.73 },
  "CM": { name: "Cameroon", allied: 1.37, economic: 2.75 },
  "CN": { name: "China", allied: 0.97, economic: 7.45 },
  "CO": { name: "Colombia", allied: 6.16, economic: 7.06 },
  "CR": { name: "Costa Rica", allied: 8.60, economic: 8.38 },
  "CU": { name: "Cuba", allied: 0.77, economic: 7.27 },
  "CV": { name: "Cape Verde", allied: 8.93, economic: 6.99 },
  "CW": { name: "Curacao", allied: 9.40, economic: 8.77 },
  "CY": { name: "Cyprus", allied: 8.78, economic: 8.43 },
  "CZ": { name: "Czechia", allied: 8.78, economic: 7.93 },
  "DE": { name: "Germany", allied: 8.93, economic: 8.60 },
  "DJ": { name: "Djibouti", allied: 2.08, economic: 3.56 },
  "DK": { name: "Denmark", allied: 9.64, economic: 8.65 },
  "DM": { name: "Dominica", allied: 8.95, economic: 5.48 },
  "DO": { name: "Dominican Republic", allied: 6.76, economic: 6.44 },
  "DZ": { name: "Algeria", allied: 3.43, economic: 6.83 },
  "EC": { name: "Ecuador", allied: 6.45, economic: 7.21 },
  "EE": { name: "Estonia", allied: 9.36, economic: 7.73 },
  "EG": { name: "Egypt", allied: 1.27, economic: 5.08 },
  "EH": { name: "Western Sahara", allied: 0.00, economic: 0.00 },
  "ER": { name: "Eritrea", allied: 0.47, economic: 4.46 },
  "ES": { name: "Spain", allied: 9.40, economic: 8.61 },
  "ET": { name: "Ethiopia", allied: 1.52, economic: 3.86 },
  "FI": { name: "Finland", allied: 9.92, economic: 8.68 },
  "FJ": { name: "Fiji", allied: 6.78, economic: 4.17 },
  "FM": { name: "Micronesia", allied: 8.91, economic: 3.87 },
  "FR": { name: "France", allied: 8.97, economic: 8.87 },
  "GA": { name: "Gabon", allied: 2.09, economic: 4.31 },
  "GB": { name: "United Kingdom", allied: 8.74, economic: 8.68 },
  "GD": { name: "Grenada", allied: 8.74, economic: 6.61 },
  "GE": { name: "Georgia", allied: 5.46, economic: 6.26 },
  "GF": { name: "French Guiana", allied: 8.97, economic: 8.87 },
  "GH": { name: "Ghana", allied: 7.66, economic: 3.35 },
  "GI": { name: "Gibraltar", allied: 9.40, economic: 8.82 },
  "GL": { name: "Greenland", allied: 9.40, economic: 8.61 },
  "GM": { name: "Gambia", allied: 5.03, economic: 3.45 },
  "GN": { name: "Guinea", allied: 3.07, economic: 2.99 },
  "GQ": { name: "Equatorial Guinea", allied: 0.25, economic: 2.61 },
  "GR": { name: "Greece", allied: 8.78, economic: 8.55 },
  "GT": { name: "Guatemala", allied: 5.05, economic: 5.85 },
  "GU": { name: "Guam", allied: 8.74, economic: 8.45 },
  "GW": { name: "Guinea-Bissau", allied: 3.54, economic: 2.97 },
  "GY": { name: "Guyana", allied: 7.14, economic: 4.79 },
  "HN": { name: "Honduras", allied: 4.44, economic: 5.85 },
  "HR": { name: "Croatia", allied: 8.47, economic: 7.63 },
  "HT": { name: "Haiti", allied: 1.43, economic: 3.19 },
  "HU": { name: "Hungary", allied: 6.78, economic: 6.99 },
  "IE": { name: "Ireland", allied: 9.57, economic: 8.82 },
  "IL": { name: "Israel", allied: 7.04, economic: 8.48 },
  "IN": { name: "India", allied: 6.20, economic: 5.47 },
  "IQ": { name: "Iraq", allied: 2.88, economic: 5.45 },
  "IR": { name: "Iran", allied: 0.79, economic: 7.35 },
  "IS": { name: "Iceland", allied: 9.45, economic: 8.89 },
  "IT": { name: "Italy", allied: 8.75, economic: 8.91 },
  "JM": { name: "Jamaica", allied: 7.66, economic: 5.42 },
  "JO": { name: "Jordan", allied: 3.17, economic: 7.29 },
  "JP": { name: "Japan", allied: 8.40, economic: 8.80 },
  "KE": { name: "Kenya", allied: 5.14, economic: 2.80 },
  "KG": { name: "Kyrgyzstan", allied: 2.27, economic: 5.35 },
  "KH": { name: "Cambodia", allied: 2.49, economic: 5.16 },
  "KI": { name: "Kiribati", allied: 7.73, economic: 3.51 },
  "KM": { name: "Comoros", allied: 4.14, economic: 3.86 },
  "KN": { name: "Saint Kitts and Nevis", allied: 8.74, economic: 5.64 },
  "KP": { name: "North Korea", allied: 0.07, economic: 6.06 },
  "KR": { name: "South Korea", allied: 8.15, economic: 8.53 },
  "KW": { name: "Kuwait", allied: 2.94, economic: 8.11 },
  "KZ": { name: "Kazakhstan", allied: 2.20, economic: 6.36 },
  "LA": { name: "Laos", allied: 1.63, economic: 4.47 },
  "LB": { name: "Lebanon", allied: 4.19, economic: 6.99 },
  "LC": { name: "Saint Lucia", allied: 8.78, economic: 5.79 },
  "LI": { name: "Liechtenstein", allied: 9.36, economic: 9.14 },
  "LK": { name: "Sri Lanka", allied: 5.75, economic: 6.96 },
  "LR": { name: "Liberia", allied: 6.16, economic: 2.39 },
  "LS": { name: "Lesotho", allied: 6.01, economic: 1.75 },
  "LT": { name: "Lithuania", allied: 8.78, economic: 6.61 },
  "LU": { name: "Luxembourg", allied: 9.52, economic: 8.70 },
  "LV": { name: "Latvia", allied: 8.74, economic: 6.63 },
  "LY": { name: "Libya", allied: 0.63, economic: 5.90 },
  "MA": { name: "Morocco", allied: 3.79, economic: 6.49 },
  "MC": { name: "Monaco", allied: 9.36, economic: 9.34 },
  "MD": { name: "Moldova", allied: 5.54, economic: 5.36 },
  "ME": { name: "Montenegro", allied: 6.24, economic: 6.96 },
  "MF": { name: "Saint Martin", allied: 8.97, economic: 8.87 },
  "MG": { name: "Madagascar", allied: 4.76, economic: 2.81 },
  "MH": { name: "Marshall Islands", allied: 9.36, economic: 3.88 },
  "MK": { name: "North Macedonia", allied: 6.28, economic: 6.93 },
  "ML": { name: "Mali", allied: 1.48, economic: 1.86 },
  "MM": { name: "Myanmar", allied: 0.50, economic: 3.88 },
  "MN": { name: "Mongolia", allied: 8.48, economic: 5.24 },
  "MO": { name: "Macau", allied: 0.97, economic: 8.24 },
  "MP": { name: "Northern Mariana Islands", allied: 8.74, economic: 8.45 },
  "MQ": { name: "Martinique", allied: 8.97, economic: 8.87 },
  "MR": { name: "Mauritania", allied: 3.54, economic: 4.32 },
  "MS": { name: "Montserrat", allied: 9.40, economic: 8.77 },
  "MT": { name: "Malta", allied: 8.56, economic: 9.17 },
  "MU": { name: "Mauritius", allied: 8.42, economic: 6.59 },
  "MV": { name: "Maldives", allied: 4.36, economic: 8.30 },
  "MW": { name: "Malawi", allied: 6.12, economic: 3.85 },
  "MX": { name: "Mexico", allied: 5.84, economic: 6.49 },
  "MY": { name: "Malaysia", allied: 4.96, economic: 6.92 },
  "MZ": { name: "Mozambique", allied: 3.87, economic: 3.09 },
  "NA": { name: "Namibia", allied: 7.10, economic: 3.98 },
  "NC": { name: "New Caledonia", allied: 8.74, economic: 8.45 },
  "NE": { name: "Niger", allied: 2.72, economic: 2.09 },
  "NF": { name: "Norfolk Island", allied: 8.74, economic: 8.45 },
  "NG": { name: "Nigeria", allied: 4.30, economic: 0.89 },
  "NI": { name: "Nicaragua", allied: 1.30, economic: 6.44 },
  "NL": { name: "Netherlands", allied: 9.52, economic: 8.68 },
  "NO": { name: "Norway", allied: 9.86, economic: 8.85 },
  "NP": { name: "नेपाल", allied: 6.14, economic: 4.94 },
  "NR": { name: "Nauru", allied: 7.27, economic: 2.30 },
  "NZ": { name: "New Zealand", allied: 9.86, economic: 8.76 },
  "OM": { name: "Oman", allied: 2.79, economic: 7.96 },
  "PA": { name: "Panama", allied: 8.33, economic: 7.98 },
  "PE": { name: "Peru", allied: 7.02, economic: 7.28 },
  "PF": { name: "French Polynesia", allied: 8.97, economic: 8.87 },
  "PG": { name: "Papua New Guinea", allied: 5.99, economic: 3.66 },
  "PH": { name: "Philippines", allied: 5.44, economic: 4.68 },
  "PK": { name: "Pakistan", allied: 2.83, economic: 5.41 },
  "PL": { name: "Poland", allied: 8.54, economic: 7.54 },
  "PM": { name: "Saint Pierre and Miquelon", allied: 8.97, economic: 8.87 },
  "PN": { name: "Pitcairn Islands", allied: 8.74, economic: 8.45 },
  "PR": { name: "Puerto Rico", allied: 8.74, economic: 8.45 },
  "PS": { name: "Palestine", allied: 3.07, economic: 6.27 },
  "PT": { name: "Portugal", allied: 9.52, economic: 8.74 },
  "PW": { name: "Palau", allied: 9.36, economic: 4.66 },
  "PY": { name: "Paraguay", allied: 7.40, economic: 6.42 },
  "QA": { name: "Qatar", allied: 2.65, economic: 8.76 },
  "RE": { name: "Reunion", allied: 8.97, economic: 8.87 },
  "RO": { name: "Romania", allied: 7.88, economic: 6.69 },
  "RS": { name: "Serbia", allied: 4.67, economic: 6.90 },
  "RU": { name: "Russia", allied: 0.57, economic: 6.20 },
  "RW": { name: "Rwanda", allied: 2.24, economic: 4.12 },
  "SA": { name: "Saudi Arabia", allied: 0.84, economic: 7.63 },
  "SB": { name: "Solomon Islands", allied: 7.12, economic: 3.73 },
  "SC": { name: "Seychelles", allied: 8.33, economic: 6.68 },
  "SD": { name: "Sudan", allied: 0.76, economic: 3.90 },
  "SE": { name: "Sweden", allied: 9.94, economic: 8.68 },
  "SG": { name: "Singapore", allied: 3.88, economic: 9.18 },
  "SH": { name: "Saint Helena", allied: 8.74, economic: 8.45 },
  "SI": { name: "Slovenia", allied: 9.36, economic: 8.54 },
  "SJ": { name: "Svalbard and Jan Mayen", allied: 9.52, economic: 8.74 },
  "SK": { name: "Slovakia", allied: 8.74, economic: 7.40 },
  "SL": { name: "Sierra Leone", allied: 4.10, economic: 2.78 },
  "SM": { name: "San Marino", allied: 9.36, economic: 9.14 },
  "SN": { name: "Senegal", allied: 6.70, economic: 4.50 },
  "SO": { name: "Somalia", allied: 0.34, economic: 1.30 },
  "SR": { name: "Suriname", allied: 6.60, economic: 6.62 },
  "SS": { name: "South Sudan", allied: 0.40, economic: 1.14 },
  "ST": { name: "Sao Tome and Principe", allied: 7.12, economic: 3.79 },
  "SV": { name: "El Salvador", allied: 3.90, economic: 5.49 },
  "SX": { name: "Sint Maarten", allied: 9.40, economic: 8.77 },
  "SY": { name: "Syria", allied: 0.47, economic: 5.58 },
  "SZ": { name: "Eswatini", allied: 5.23, economic: 2.83 },
  "TC": { name: "Turks and Caicos Islands", allied: 9.40, economic: 8.77 },
  "TD": { name: "Chad", allied: 2.76, economic: 1.71 },
  "TF": { name: "French Southern Territories", allied: 8.97, economic: 8.87 },
  "TG": { name: "Togo", allied: 4.18, economic: 2.69 },
  "TH": { name: "Thailand", allied: 3.96, economic: 6.92 },
  "TJ": { name: "Tajikistan", allied: 0.20, economic: 5.40 },
  "TK": { name: "Tokelau", allied: 8.74, economic: 8.45 },
  "TL": { name: "East Timor", allied: 6.95, economic: 3.77 },
  "TM": { name: "Turkmenistan", allied: 0.20, economic: 6.00 },
  "TN": { name: "Tunisia", allied: 6.54, economic: 7.40 },
  "TO": { name: "Tonga", allied: 8.74, economic: 3.51 },
  "TR": { name: "Turkey", allied: 5.17, economic: 7.35 },
  "TT": { name: "Trinidad and Tobago", allied: 8.33, economic: 6.72 },
  "TV": { name: "Tuvalu", allied: 8.97, economic: 3.59 },
  "TW": { name: "Taiwan", allied: 9.20, economic: 8.20 },
  "TZ": { name: "Tanzania", allied: 3.67, economic: 3.78 },
  "UA": { name: "Ukraine", allied: 5.74, economic: 6.44 },
  "UG": { name: "Uganda", allied: 3.72, economic: 3.84 },
  "UM": { name: "United States Minor Outlying Islands", allied: 8.74, economic: 8.45 },
  "US": { name: "United States", allied: 8.18, economic: 7.78 },
  "UY": { name: "Uruguay", allied: 9.16, economic: 7.27 },
  "UZ": { name: "Uzbekistan", allied: 1.30, economic: 5.44 },
  "VA": { name: "Holy See", allied: 9.36, economic: 9.14 },
  "VC": { name: "Saint Vincent and the Grenadines", allied: 8.74, economic: 5.63 },
  "VE": { name: "Venezuela", allied: 0.95, economic: 5.70 },
  "VG": { name: "British Virgin Islands", allied: 9.40, economic: 8.77 },
  "VI": { name: "United States Virgin Islands", allied: 8.74, economic: 8.45 },
  "VN": { name: "Vietnam", allied: 1.76, economic: 6.26 },
  "VU": { name: "Vanuatu", allied: 7.77, economic: 5.21 },
  "WF": { name: "Wallis and Futuna", allied: 8.74, economic: 8.45 },
  "WS": { name: "Samoa", allied: 7.93, economic: 5.29 },
  "XK": { name: "Kosovo", allied: 5.24, economic: 6.22 },
  "YE": { name: "Yemen", allied: 0.84, economic: 4.62 },
  "YT": { name: "Mayotte", allied: 8.97, economic: 8.87 },
  "ZA": { name: "South Africa", allied: 7.84, economic: 3.63 },
  "ZM": { name: "Zambia", allied: 4.53, economic: 3.74 },
  "ZW": { name: "Zimbabwe", allied: 2.40, economic: 2.60 }
};
